=== enriquee17/TrabajoEnClase/TrabajoEnClase/src/LenguajedeMarcas/correo.dtd
<!ELEMENT emails (email*)>
<!ELEMENT email (para*, cc*, cco*, asunto, cuerpo, adjunto*)>

<!ELEMENT para (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT cco (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>
<!ELEMENT adjunto (nombre, mimetype, longitud)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mimetype (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>

=== enriquee17/TrabajoEnClase/TrabajoEnClase/src/LenguajedeMarcas/ejerciciocorreo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE placasbaseejercicio SYSTEM "correo.dtd"> 
<emails>
	<email>
		<para>enripoor@hotmail.com</para>
		<cc></cc>
		<cco></cco>
		<asunto>sdgsfs</asunto>
		<cuerpo></cuerpo>
		<adjunto>
			<nombre></nombre>
			<mimetype></mimetype>
			<longitud></longitud>
		</adjunto>	
	</email>
</emails>
