=== enriquee17/TrabajoEnClase/TrabajoEnClase/src/LenguajedeMarcas/LosSimpsons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="simpsons" type="tipoSimpsons"/>

	<xs:complexType name="tipoSimpsons">
	
		<xs:sequence>
		
			<xs:element name="localidad" type="tipoLocalidad"/>	
			<xs:element name="pelicula" type="tipoPelicula"/>
			<xs:element name="creador" type="tipoCreador"/>
			<xs:element name="familia" type="tipoFamilia"/>
			<xs:element name="temporadas" type="tipoTemporada"/>
			<xs:element name="personajes" type="tipoPersonaje"/>
			<xs:element name="colorPersonajes" type="tipoColor"/>
			<xs:element name="MontgomeryBurns" type="tipoMont"/>
				
		</xs:sequence>
		
	</xs:complexType>
	
	<!-- Diferentes atributos -->
	
	
	<xs:complexType name="tipoLocalidad">
				
		<xs:attribute name="valor" type="xs:string"/>
		<xs:attribute name="aÃ±oFundacion" type="xs:integer"></xs:attribute>
				
	</xs:complexType>
	
	<!-- Contenido mixto -->
	
	<xs:complexType mixed="true" name="tipoPelicula">
				
		<xs:sequence>
					
			<xs:element name="titulo" type="xs:string"/>
					
		</xs:sequence>
			
	</xs:complexType>
	
	<!-- Atributo y contenido de texto -->
	
	
	<xs:complexType name="tipoCreador" mixed="true">
	
		<xs:attribute name="bso" type="xs:string"/>
	
	</xs:complexType>
	
	<!-- Atributo y contenido numerico -->
	
	<xs:complexType name="tipoFamilia">
	
		<xs:simpleContent>
		
            <xs:extension base="xs:integer">
            
            	<xs:attribute name="nombre" type="xs:string"/>
            
            </xs:extension>
		
		</xs:simpleContent>
	
	</xs:complexType>
	
	<!-- Uso de xs:choice -->
	
	<xs:complexType name="tipoTemporada">
	
		<xs:choice>
		
			<xs:element name="temporada01" type="xs:string"/>	
			
			<xs:element name="temporada02" type="xs:string"/>
			<xs:element name="temporada03" type="xs:string"/>
			
		
		</xs:choice>
	
	</xs:complexType>
	
	<!-- Uso de xs:all -->
	<xs:complexType name="tipoPersonaje">
	
		<xs:all>
		
			<xs:element name="Hommer" type="tipoVacio"/>
			<xs:element name="Marge" type="tipoVacio"/>
			<xs:element name="Bart" type="tipoVacio"/>
			<xs:element name="Lisa" type="tipoVacio"/>
			<xs:element name="Maggie" type="tipoVacio"/>
		
		</xs:all>
	
	</xs:complexType>
	
	<xs:complexType name="tipoVacio"></xs:complexType>
	
	<!-- lista de posibles valores -->
	<xs:complexType name="tipoColor">
	
		<xs:attribute name="principal">
		
			<xs:simpleType>
			
				<xs:restriction base="xs:string">
				
					<xs:enumeration value="amarillo"/>
					<xs:enumeration value="negro"/>
					<xs:enumeration value="rojo"/>
					
				</xs:restriction>
			
			</xs:simpleType>
		
		</xs:attribute>
		
		<xs:attribute name="rojo" type="valorEntre100y1000"></xs:attribute>
		<xs:attribute name="verde" type="valorEntre100y1000"></xs:attribute>
		<xs:attribute name="azul" type="valorEntre100y1000"></xs:attribute>
	
	</xs:complexType>
	
	<!-- Valor entre 100 y 1000 -->
	<xs:simpleType name="valorEntre100y1000">
	
		<xs:restriction base="xs:integer">
		
			<xs:minInclusive value="100"></xs:minInclusive>
			<xs:maxExclusive value="1000"></xs:maxExclusive>
		
		</xs:restriction>
	
	</xs:simpleType>
	
	<!-- dni -->
	<xs:complexType name="tipoMont">
	
		<xs:attribute name="dni">

			<xs:simpleType>
			
				<xs:restriction base="xs:string">
				
					<xs:pattern value="\d{8}[A-Z]"/>
				
				</xs:restriction>
			
			</xs:simpleType>		

		</xs:attribute>	
		
		<!-- matricula -->
		<xs:attribute name="matricula">

			<xs:simpleType>
			
				<xs:restriction base="xs:string">
				
					<xs:pattern value="[0-9]{4}[A-Z]{3}"/>
				
				</xs:restriction>
			
			</xs:simpleType>		

		</xs:attribute>	
		
		<!-- mac -->
		<xs:attribute name="mac">

			<xs:simpleType>
			
				<xs:restriction base="xs:string">
				
					<xs:pattern value="([0-9|A-F|a-f]{2}:){5}[0-9|A-F|a-f]{2}"/>
				
				</xs:restriction>
			
			</xs:simpleType>		

		</xs:attribute>	
		
		<!-- color -->
		<xs:attribute name="color">

			<xs:simpleType>
			
				<xs:restriction base="xs:string">
				
					<xs:pattern value="(amarillo)|(rojo)|(negro)"/>
				
				</xs:restriction>
			
			</xs:simpleType>		

		</xs:attribute>	
	
	</xs:complexType>
	

	
			
	
</xs:schema>

=== enriquee17/TrabajoEnClase/TrabajoEnClase/src/LenguajedeMarcas/LosSimpsons.xml
<?xml version="1.0" encoding="UTF-8"?>
<simpsons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LosSimpsons.xsd">
	
	<localidad valor="Springfield" aÃ±oFundacion="1800"/>
	
	<pelicula>Estreno el dia 15-03-2012 	
		<titulo>Los Simpsons la pelicula</titulo>
	
	</pelicula>
	
	<creador bso="Danny Elfman">Matt Groening</creador>
	
	<familia nombre="Simpsons">5</familia>
	
	<temporadas>
	
		<temporada01/>
		
	</temporadas>
	
	<personajes>
		<Hommer/>
		<Marge/>
		<Bart/>
		<Lisa/>
		<Maggie/>
	
	</personajes>
	
	<colorPersonajes principal="amarillo" rojo="120" verde="150" azul="700"/>
	
	<MontgomeryBurns dni="12345678A" matricula="0001ABC" mac="14:e3:a5:34:87:ef" color="rojo"/>
	
	<localidadRival>San_Francisco</localidadRival> 
	<localidadAmiga>San_Francsco</localidadAmiga>
	
	

</simpsons>
