=== enriquee17/TrabajoEnClase/TrabajoEnClase/src/LenguajedeMarcas/ModelosYMarcas.dtd
<!ELEMENT ModelosYMarcas (Coches)>
<!ELEMENT Coches (TipoDeCoche, Colores, Color)>
<!ELEMENT Colores EMPTY>
<!ELEMENT Color EMPTY>
<!ELEMENT TipoDeCoche (Deportivo+, Berlina*, TodoTerreno*)>
<!ELEMENT Deportivo (Marca, Modelo, Potencia?, A単o)>
<!ELEMENT Berlina EMPTY>
<!ELEMENT TodoTerreno (Marca, Modelo, Potencia?, A単o)>
<!ELEMENT Marca (#PCDATA)>
<!ELEMENT Modelo (#PCDATA)>
<!ELEMENT Potencia (#PCDATA)>
<!ELEMENT A単o EMPTY>
<!ATTLIST A単o fecha (2000 | 2001 | 2002) #IMPLIED>
<!ATTLIST Modelo color ID #REQUIRED>
<!ATTLIST Modelo Puertas CDATA #FIXED "4">
<!ENTITY interior "Este coche tiene un interior muy lujoso">
<!ATTLIST Color color IDREF #REQUIRED>
<!ATTLIST Colores colores IDREFS #REQUIRED>

=== enriquee17/TrabajoEnClase/TrabajoEnClase/src/LenguajedeMarcas/ModelosYMarcas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelosYMarcas SYSTEM "ModelosYMarcas.dtd">
<ModelosYMarcas>
	<Coches>
		<TipoDeCoche>
			<Deportivo>
				<Marca>Ferrari</Marca>
				<Modelo color="Rojo" Puertas="4">E2 &interior;</Modelo>
				<Potencia>400caballos</Potencia>
				<A単o fecha="2002"/>
			</Deportivo>
			<Berlina></Berlina>
			<TodoTerreno>
				<Marca>LangeRover</Marca>
				<Modelo color="Negro">45</Modelo>
				<Potencia>150caballos</Potencia>
				<A単o fecha="2000" />
			</TodoTerreno>
			<TodoTerreno>
				<Marca>LangeRover</Marca>
				<Modelo color="Blanco"/>
				<Potencia>150caballos</Potencia>
				<A単o></A単o>
			</TodoTerreno>
		</TipoDeCoche>
		<Colores colores="Rojo Negro Blanco"></Colores>
		<Color color="Blanco"/>
		</Coches>
</ModelosYMarcas>
